language: python

python: 2.7

sudo: false

cache: pip

install:
  - pip uninstall -y userdatamodel || true
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt
  - python setup.py install

script:
  - py.test -vv --cov=authutils --cov-report xml tests

after_script:
  - python-codacy-coverage -r coverage.xml
